global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'docker-host-alpha'

scrape_configs:
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'dev-server'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: ['dev.topskill.uz:443']
    metrics_path: "/metrics"
    basic_auth:
      username: ADMIN_USER
      password: ADMIN_PASSWORD

#  - job_name: "dev-docker"
#    static_configs:
#      - targets: ["165.22.103.111:9323"]
#    basic_auth:
#      username: ADMIN_USER
#      password: ADMIN_PASSWORD